### ISSUE TITLE
无法安装啊

### ISSUE THREAD

**Issue by sherry255** [MrKiven/Todo.py#11]

**Comment by sherry255** [comment]
long_description=open("README.md").read(),
    IOError: [Errno 2] No such file or directory: 'README.md'

**Comment by MrKiven** [comment]
sorry!  Fixed now.

Run `pip install todos`

**Comment by Letme** [comment]
This still seems like it is not fixed on the pip today. Maybe it requires update?

**Comment by Letme** [comment]
The new error is:
```
Using cached https://files.pythonhosted.org/packages/33/a7/083d67ca6cb910122d3199e93dfb0a5fea1a34b935709954a06c122986f7/todos-0.2.1.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-q76nb4uc/todos/setup.py", line 20, in <module>
        with open("README.md") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-q76nb4uc/todos/
```
